variables:
    GIT_DEPTH: "1"

stages:
    - build_deb
    - ready_to_upload

build_deb:
    tags:
        - Runner-Stretch
    stage: build_deb
    script:
        - echo "deb http://ibg-linux-apt.moxa.com:8080/mirror-stretch/Debian9.13_20200718 stretch main" > /etc/apt/sources.list
        - curl -fsSL http://ibg-linux-apt.moxa.com:8080/ibg-linux-apt.gpg | apt-key add -
        - apt-get update
        - apt-get install -y -qq --no-install-recommends build-essential devscripts
        - apt-get build-dep ./ -y
        - dpkg-buildpackage -us -uc
        - mv ../*.buildinfo .
        - mv ../*.changes .
        - mv ../*.deb .
        - mv ../*.tar.gz .
        - mv ../*.dsc .
    artifacts:
        name: "${CI_PROJECT_NAME}"
        paths:
        - ./*.buildinfo
        - ./*.changes
        - ./*.deb
        - ./*.tar.gz
        - ./*.dsc

ready_to_upload:
    tags:
        - Runner-Stretch
    stage: ready_to_upload
    only:
      refs:
        - stretch/master
    dependencies:
        - build_deb
    when: manual
    script:
        - mkdir -p /cache/stretch/mil1-internal-release/
        - cp *.deb *.dsc *.tar.gz /cache/stretch/mil1-internal-release/
        - ls /cache/stretch/mil1-internal-release/
